package utilities.AIHackathon;

public class HtmlChecks_AIHackathon {

	public static final String Table_HTML = "<table id=\"transactionsTable\" class=\"table table-padded\">\n"
			+ "                    <thead>\n" + "                     <tr>\n"
			+ "                        <th id=\"status\" onclick=\"sortTable(0)\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Status\n" + "                        </th>\n"
			+ "                        <th id=\"date\" onclick=\"sortTable(1)\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Date\n" + "                        </th>\n"
			+ "                        <th id=\"description\" onclick=\"sortTable(2)\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Description\n" + "                        </th>\n"
			+ "                        <th id=\"category\" onclick=\"sortTable(3)\" class=\"text-center\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Category\n" + "                        </th>\n"
			+ "                        <th id=\"amount\" onclick=\"sortTable(4)\" class=\"text-right\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Amount\n" + "                        </th>\n" + "                      </tr>\n"
			+ "                    </thead>\n" + "                    <tbody>\n" + "                      <tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller green\"></span><span>Complete</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Today</span><span class=\"smaller lighter\">1:52am</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company1.png\" style=\"height: 25px;\"><span>Starbucks coffee</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-success\" href=\"\">Restaurant / Cafe</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-success\">+ 1,250.00 USD</span>\n"
			+ "                        </td>\n" + "                      </tr>\n" + "                      <tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller red\"></span><span>Declined</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Jan 19th</span><span class=\"smaller lighter\">3:22pm</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company2.png\" style=\"height: 25px;\"><span>Stripe Payment Processing</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-danger\" href=\"\">Finance</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-success\">+ 952.23 USD</span>\n"
			+ "                        </td>\n" + "                      </tr>\n" + "                      <tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller yellow\"></span><span>Pending</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Yesterday</span><span class=\"smaller lighter\">7:45am</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company3.png\" style=\"height: 25px;\"><span>MailChimp Services</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-warning\" href=\"\">Software</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-danger\">- 320.00 USD</span>\n"
			+ "                        </td>\n" + "                      </tr>\n" + "                      <tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller yellow\"></span><span>Pending</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Jan 23rd</span><span class=\"smaller lighter\">2:7pm</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company6.png\" style=\"height: 25px;\"><span>Shopify product</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-primary\" href=\"\">Shopping</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-success\">+ 17.99 USD</span>\n"
			+ "                        </td>\n" + "                      </tr>\n" + "                      <tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller green\"></span><span>Complete</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Jan 7th</span><span class=\"smaller lighter\">9:51am</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company4.png\" style=\"height: 25px;\"><span>Ebay Marketplace</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-danger\" href=\"\">Ecommerce</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-danger\">- 244.00 USD</span>\n"
			+ "                        </td>\n" + "                      </tr>\n" + "                      <tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller yellow\"></span><span>Pending</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Jan 9th</span><span class=\"smaller lighter\">7:45pm</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company7.png\" style=\"height: 25px;\"><span> Templates Inc</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-primary\" href=\"\">Business</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-success\">+ 340.00 USD</span>\n"
			+ "                        </td>\n" + "                      </tr>\n" + "                    </tbody>\n"
			+ "                  </table>";

	public static final String Table_HTLM_After = "<table id=\"transactionsTable\" class=\"table table-padded\">\n"
			+ "                    <thead>\n" + "                      <tr>\n"
			+ "                        <th id=\"status\" onclick=\"sortTable(0)\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Status\n" + "                        </th>\n"
			+ "                        <th id=\"date\" onclick=\"sortTable(1)\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Date\n" + "                        </th>\n"
			+ "                        <th id=\"description\" onclick=\"sortTable(2)\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Description\n" + "                        </th>\n"
			+ "                        <th id=\"category\" onclick=\"sortTable(3)\" class=\"text-center\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Category\n" + "                        </th>\n"
			+ "                        <th id=\"amount\" onclick=\"sortTable(4)\" class=\"text-right\" onmouseover=\"\" style=\"cursor: pointer;\">\n"
			+ "                          Amount\n" + "                        </th>\n" + "                      </tr>\n"
			+ "                    </thead>\n" + "                    <tbody>\n" + "                      <tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller yellow\"></span><span>Pending</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Yesterday</span><span class=\"smaller lighter\">7:45am</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company3.png\" style=\"height: 25px;\"><span>MailChimp Services</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-warning\" href=\"\">Software</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-danger\">- 320.00 USD</span>\n"
			+ "                        </td>\n" + "                      </tr><tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller green\"></span><span>Complete</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Jan 7th</span><span class=\"smaller lighter\">9:51am</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company4.png\" style=\"height: 25px;\"><span>Ebay Marketplace</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-danger\" href=\"\">Ecommerce</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-danger\">- 244.00 USD</span>\n"
			+ "                        </td>\n" + "                      </tr><tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller yellow\"></span><span>Pending</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Jan 23rd</span><span class=\"smaller lighter\">2:7pm</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company6.png\" style=\"height: 25px;\"><span>Shopify product</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-primary\" href=\"\">Shopping</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-success\">+ 17.99 USD</span>\n"
			+ "                        </td>\n" + "                      </tr><tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller yellow\"></span><span>Pending</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Jan 9th</span><span class=\"smaller lighter\">7:45pm</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company7.png\" style=\"height: 25px;\"><span> Templates Inc</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-primary\" href=\"\">Business</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-success\">+ 340.00 USD</span>\n"
			+ "                        </td>\n" + "                      </tr><tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller red\"></span><span>Declined</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Jan 19th</span><span class=\"smaller lighter\">3:22pm</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company2.png\" style=\"height: 25px;\"><span>Stripe Payment Processing</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-danger\" href=\"\">Finance</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-success\">+ 952.23 USD</span>\n"
			+ "                        </td>\n" + "                      </tr><tr>\n"
			+ "                        <td class=\"nowrap\">\n"
			+ "                          <span class=\"status-pill smaller green\"></span><span>Complete</span>\n"
			+ "                        </td>\n" + "                        <td>\n"
			+ "                          <span>Today</span><span class=\"smaller lighter\">1:52am</span>\n"
			+ "                        </td>\n" + "                        <td class=\"cell-with-media\">\n"
			+ "                          <img alt=\"\" src=\"img/company1.png\" style=\"height: 25px;\"><span>Starbucks coffee</span>\n"
			+ "                        </td>\n" + "                        <td class=\"text-center\">\n"
			+ "                          <a class=\"badge badge-success\" href=\"\">Restaurant / Cafe</a>\n"
			+ "                        </td>\n" + "                        <td class=\"text-right bolder nowrap\">\n"
			+ "                          <span class=\"text-success\">+ 1,250.00 USD</span>\n"
			+ "                        </td>\n" + "                      </tr>\n" + "                      \n"
			+ "                      \n" + "                      \n" + "                      \n"
			+ "                      \n" + "                    </tbody>\n" + "                  </table>";

}
